---
- name: tournament_go
  hosts: bot
  become_method: sudo
  become: yes
  become_user: root

  vars:
    ansible_user: root
    ansible_ssh_private_key: "{{ key }}"
    ansible_port: 22
    ansible_connection: ssh
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'

  tasks:

  - name: start a container
    community.docker.docker_container:
      name: myapp
      image: foilv/tournament_go:91d77ffd68d97b29f5235f67f81892d719697803
      state: started
      env: 
        HOST: "172.17.0.2" 
        DATABASE: "tournament_go"
        USER: "{{ loginroot }}"
        PASSWORD: "{{ passroot }}"
        BOT: "{{ bot }}"

