---
- name: tournament_go
  hosts: bot
  become_method: sudo
  become: yes
  become_user: root

  vars:
    ansible_user: foilv
    ansible_ssh_private_key: "{{ key }}"
    ansible_port: 22
    ansible_connection: ssh
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'

  tasks:

  # - name: pull an image
  #   docker_image:
  #     name: foilv/tournaments_go:3
  #     source: pull
  #     debug: true

  - name: Create database user 
    community.mysql.mysql_user:
      name: "foilv"
      password: "{{ PASSWORD }}"
      login_unix_socket: /var/run/mysqld/mysqld.sock
      priv: '*.*:ALL,GRANT'
      host: '%'
      state: present

  - name: start a container
    community.docker.docker_container:
      name: Bot
      image: "tournaments_go:bot4"
      state: started
      env: 
        PASSWORD: "{{ PASSWORD }}"
        HOST: "194.32.248.108:3306" 
        DATABASE: "tournament_go"
        USER: "foilv"
        BOT: "{{ bot }}"

