---
- name: tournament_go
  hosts: bot
  become_method: sudo
  become: yes
  become_user: root

  vars:
    ansible_user: foilv
    ansible_ssh_private_key: "{{ key }}"
    ansible_port: 22
    ansible_connection: ssh
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'

  tasks:

  - name: Create database user 
    community.mysql.mysql_user:
      name: "foilv"
      password: "{{ PASSWORD }}"
      login_unix_socket: /var/run/mysqld/mysqld.sock
      priv: '*.*:ALL,GRANT'
      host: '%'
      state: present

  - name: start a container
    community.docker.docker_container:
      name: Bot
      image: foilv/tournaments_go:bot10
      state: started
      env:
        HOST: "{{ HOST }}"
        DATABASE: "tournament_go"
        USER: "foilv"
        PASSWORD: "{{ PASSWORD }}"
        BOT: "{{ BOT }}"


