---
- name: tournament_go
  hosts: bot
  become_method: sudo
  become: yes
  become_user: root

  vars:
    ansible_user: root
    ansible_ssh_private_key: "{{ key }}"
    ansible_port: 22
    ansible_connection: ssh
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'

  tasks:

  - name: start a container
    community.docker.docker_container:
      name: myapp
      image: foilv/tournament_go
      state: started
      env: 
        HOST: "194.32.248.108" 
        DATABASE: "tournament_go"
        USER: "{{ loginroot }}"
        #PASSWORD: "{{ newuserpass }}"
        BOT: "{{ bot }}"

