name: Docker

on: [ push ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: sed 
        run: cat secret1.json | sed -i -e 's|BOT|'${{ secrets.BOT }}'|g' secret1.json -i -e 's|LOGIN_ROOT|'${{ secrets.LOGIN_ROOT }}'|g' secret1.json -i -e 's|PASS_ROOT|'${{ secrets.PASS_ROOT }}'|g' secret1.json -i -e 's|DEPLOY_SERVER_KEY|'${{ secrets.DEPLOY_SERVER_KEY }}'|g' secret1.json

      - name: install authorized key id_rsa.pub
        env:
          DEPLOY_SERVER_KEY: ${{ secrets.DEPLOY_SERVER_KEY }}
        run: echo $DEPLOY_SERVER_KEY | base64 --decode > key | chmod 0600 key

      - name: run playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
        run: ansible-playbook -i inventory.yml playbook.yml -u foilv --extra-vars "@secret1.json"

          
          