name: Docker

on: [ push ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: login docker hub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        
      - name: build and push docker image
        uses: docker/build-push-action@v2
        id: docker_build
        with: 
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/tournament_go:latest

      - name: Verify
        run: echo ${{ steps.docker_build.outputs.digest }} #ok

          
          