name: Docker

on: [ push ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: sed 
        run: cat secret1.json | sed -i -e 's|ROOT|'${{ secrets.ROOT }}'|g' secret1.json -i -e 's|BOT1|'${{ secrets.BOT }}'|g' secret1.json -i -e 's|LOGFOIL|'${{ secrets.LOGIN_ROOT }}'|g' secret1.json -i -e 's|FPASSW|'${{ secrets.PASS_ROOT }}'|g' secret1.json -i -e 's|DEPLOY_SERVER_KEY|'${{ secrets.DEPLOY_SERVER_KEY }}'|g' secret1.json

      - name: install authorized key id_rsa.pub
        env:
          DEPLOY_SERVER_KEY: ${{ secrets.DEPLOY_SERVER_KEY }}
        run: echo $DEPLOY_SERVER_KEY | base64 --decode > key | chmod 0600 key

      - name: run playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
        run: ansible-playbook -i inventory.yml playbook.yml --extra-vars "@secret1.json"

      - name: run docker
        run: sudo docker run foilv/tournaments_go:bot9
        env: 
          HOST: 194.32.248.108
          DATABASE: tournament_go
          USER: foilv
          PASSWORD: $(cat secret1.json | jq '.PASSWORD')
          BOT: $(cat secret1.json | jq '.BOT')


          
          